### PR TITLE
release fixes and breadcrumbs

### LINKED ISSUE #44: Fix alignment of notebook table rows
# Reliquery-UI Issue Report
Thank you for raising our awareness of an Issue with Reliquery-UI. Before submitting this Issue report check and make sure there aren't any duplicate Issues currently open. Please give as much detail about the issue as you can to help us try and resolve it.

## Prerequisites

- [ ] Are you running the latest version?

## Expected Behavior
for the metadata to line up with the table column heads

## Actual Behavior
shifted to the right

## Steps to Reproduce the Problem

  1.Open [link](https://meta.deveffect.io/reliquery/demo/neuromatch/notebook/) and click on notebook accordian dropdown.

## Your Environment
```shell
$ pip freeze

alabaster==0.7.12
anyio @ file:///home/conda/feedstock_root/build_artifacts/anyio_1636638323459/work/dist
argon2-cffi @ file:///tmp/build/80754af9/argon2-cffi_1613037499734/work
asgiref==3.4.1
async-generator==1.10
attrs @ file:///home/conda/feedstock_root/build_artifacts/attrs_1620387926260/work
Babel @ file:///home/conda/feedstock_root/build_artifacts/babel_1619719576210/work
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
black==21.11b0
bleach @ file:///home/conda/feedstock_root/build_artifacts/bleach_1629908509068/work
boto3==1.20.8
botocore==1.23.8
brotlipy==0.7.0
certifi==2021.10.8
cffi @ file:///tmp/build/80754af9/cffi_1625814692085/work
chardet @ file:///home/conda/feedstock_root/build_artifacts/chardet_1635814836324/work
charset-normalizer @ file:///home/conda/feedstock_root/build_artifacts/charset-normalizer_1626371162869/work
click==8.0.3
cryptography @ file:///home/conda/feedstock_root/build_artifacts/cryptography_1634230275410/work
cycler==0.11.0
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1631346842025/work
defusedxml @ file:///home/conda/feedstock_root/build_artifacts/defusedxml_1615232257335/work
dnspython==2.1.0
docutils==0.17.1
email-validator==1.1.3
entrypoints @ file:///home/conda/feedstock_root/build_artifacts/entrypoints_1605121927639/work/dist/entrypoints-0.3-py2.py3-none-any.whl
fastapi==0.70.0
flake8==4.0.1
fonttools==4.28.1
h11==0.12.0
httptools==0.2.0
idna @ file:///home/conda/feedstock_root/build_artifacts/idna_1609836280497/work
imagesize==1.3.0
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1636431527844/work
importlib-resources @ file:///home/conda/feedstock_root/build_artifacts/importlib_resources_1635615662634/work
iniconfig==1.1.1
ipykernel @ file:///home/conda/feedstock_root/build_artifacts/ipykernel_1620912942381/work/dist/ipykernel-5.5.5-py3-none-any.whl
ipython @ file:///home/conda/feedstock_root/build_artifacts/ipython_1636764703066/work
ipython-genutils==0.2.0
itsdangerous==2.0.1
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1635824010494/work
Jinja2 @ file:///home/conda/feedstock_root/build_artifacts/jinja2_1636510082894/work
jmespath==0.10.0
json5 @ file:///home/conda/feedstock_root/build_artifacts/json5_1600692310011/work
jsonschema @ file:///home/conda/feedstock_root/build_artifacts/jsonschema_1636165360877/work
jupyter-client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1633454794268/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1636814260563/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1635811281209/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1637169796215/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1632590716858/work
kiwisolver==1.3.2
MarkupSafe @ file:///home/conda/feedstock_root/build_artifacts/markupsafe_1621455668600/work
matplotlib==3.5.0
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1631080358261/work
mccabe==0.6.1
mistune @ file:///home/conda/feedstock_root/build_artifacts/mistune_1624941317779/work
mypy-extensions==0.4.3
nbclassic @ file:///home/conda/feedstock_root/build_artifacts/nbclassic_1635436909771/work
nbclient @ file:///home/conda/feedstock_root/build_artifacts/nbclient_1636722651147/work
nbconvert @ file:///home/conda/feedstock_root/build_artifacts/nbconvert_1636897222956/work
nbformat @ file:///home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/work
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1617163391303/work
notebook @ file:///home/conda/feedstock_root/build_artifacts/notebook_1637122013008/work
numpy==1.21.4
orjson==3.6.4
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1625323647219/work
pandas==1.3.4
pandocfilters @ file:///home/conda/feedstock_root/build_artifacts/pandocfilters_1631603243851/work
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1617148930513/work
pathspec==0.9.0
pexpect @ file:///home/conda/feedstock_root/build_artifacts/pexpect_1602535608087/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==8.4.0
platformdirs==2.4.0
pluggy==1.0.0
prometheus-client @ file:///home/conda/feedstock_root/build_artifacts/prometheus_client_1635538335951/work
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1636045889479/work
ptyprocess @ file:///home/conda/feedstock_root/build_artifacts/ptyprocess_1609419310487/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py==1.11.0
pycodestyle==2.8.0
pycparser @ file:///home/conda/feedstock_root/build_artifacts/pycparser_1636257122734/work
pydantic==1.8.2
pyflakes==2.4.0
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1629119114968/work
pyOpenSSL @ file:///home/conda/feedstock_root/build_artifacts/pyopenssl_1633192417276/work
pyparsing @ file:///home/conda/feedstock_root/build_artifacts/pyparsing_1636757021002/work
pyrsistent @ file:///tmp/build/80754af9/pyrsistent_1636110951836/work
PySocks @ file:///home/conda/feedstock_root/build_artifacts/pysocks_1635862404942/work
pytest==6.2.5
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
python-dotenv==0.19.2
python-multipart==0.0.5
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1633452062248/work
PyYAML==5.4.1
pyzmq==19.0.2
regex==2021.11.10
reliquery==0.2.9
reliquery-ui==0.2.2
requests @ file:///home/conda/feedstock_root/build_artifacts/requests_1626393743643/work
s3transfer==0.5.0
Send2Trash @ file:///home/conda/feedstock_root/build_artifacts/send2trash_1628511208346/work
setuptools-scm==6.3.2
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
sniffio @ file:///home/conda/feedstock_root/build_artifacts/sniffio_1635844660462/work
snowballstemmer==2.2.0
Sphinx==4.3.0
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
starlette==0.16.0
terminado @ file:///home/conda/feedstock_root/build_artifacts/terminado_1636052205136/work
testpath @ file:///home/conda/feedstock_root/build_artifacts/testpath_1621261527237/work
toml==0.10.2
tomli==1.2.2
tornado @ file:///home/conda/feedstock_root/build_artifacts/tornado_1610094708661/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1635260543454/work
typing_extensions==4.0.0
ujson==4.2.0
urllib3 @ file:///home/conda/feedstock_root/build_artifacts/urllib3_1632350318291/work
uvicorn==0.15.0
uvloop==0.16.0
watchgod==0.7
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1600965781394/work
webencodings==0.5.1
websocket-client @ file:///home/conda/feedstock_root/build_artifacts/websocket-client_1636990939222/work
websockets==10.1
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1633302054558/work

```
* Version used: reliquery==0.2.9 & reliquery-ui==0.2.2

**Expected behavior**

**Screenshots**
[Image of misaligned table row](https://meta.deveffect.io/reliquery/demo/dev-team/issues/images/notebook-ui-issue-1.png)

**Desktop (please complete the following information):**
 - OS: Popos 21.04
 - Browser Chrome
 - Version 95.0.4638.69 (Official Build) (64-bit)

### LINKED ISSUE #49: Remove "brand" from main menu.
# Reliquery-UI Issue Report
Thank you for raising our awareness of an Issue with Reliquery-UI. Before submitting this Issue report check and make sure there aren't any duplicate Issues currently open. Please give as much detail about the issue as you can to help us try and resolve it.

## Prerequisites

- [x] Are you running the latest version?

## Description of Issue

Currently there is the word "brand" on the hero card for each item "relics" "storages" "relic types"

Go here:
https://meta.deveffect.io/dashboard 

rq_brand

## Expected Behavior

Not to have brand

## Actual Behavior

It has brand

## Steps to Reproduce the Problem
Go here:
https://meta.deveffect.io/dashboard 

## Possible Solution

Remove brand from the code.

### PR DESCRIPTION
**Pull request by AntiAnt**
# Reliquery Pull Request
**Thank you for contributing to Reliquery.** 
Before submitting this PR please make sure:

### PR checklist
- [x] Your code builds clean without any errors or warnings
- [x] Code is formatted using the supported linter locally before pushing changes
- [x] You have added unit tests where applicable 
- [x] All tests complete and pass with changes locally
- [x] Have updated the documentation accordingly.

### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Describe proposed changes
- Added breadcrumbs 
- fixed notebook table row alignment Closes #44 
- removed "brand" from cards  on dashboard Closes #49

### CODE REVIEW

File: frontend/relic-table.tsx [hunk 1]
```diff
@@ -81,6 +84,19 @@ export const RelicTable = () => {
...
+                <BreadcrumbItem>
+                    <BreadcrumbLink href='/'>Home</BreadcrumbLink>
+                </BreadcrumbItem>
+
+                <BreadcrumbItem>
+                    <BreadcrumbLink href='/dashboard'>Dashboard</BreadcrumbLink>
+                </BreadcrumbItem>
+
+                <BreadcrumbItem isCurrentPage>
+                    <BreadcrumbLink href="/dashboard/">Relics</BreadcrumbLink>
```
Comment (ibebrett) [inline frontend/relic-table.tsx:97]: this looks like its going to the wrong place to me? Or is this final item "dead" anyway?

File: reliquery_ui/routers/relics.py [hunk 2]
```diff
@@ -201,7 +201,6 @@ async def reliquery_notebooks(
         "/reliquery/{storage_name}/{relic_type}/{name}/notebooks/{notebooks_name}",
         response_class=Response,
     )
-    @cache_no_store
```
Comment (ibebrett) [inline reliquery_ui/routers/relics.py:204]: is this removal of the cache thing on purpose?

**Review by ibebrett — APPROVED** [review]
